### ISSUE TITLE
AddGenieVtxTime does not include propogate time from POT to flux window using SBND GSimple flux file

### ISSUE THREAD

**Issue by VCLanNguyen** [NuSoftHEP/nugen#3]
Turning on AddGenieVtx fcl parameter on using SBND GSimple flux file input currently only includes propagation time from flux window to interaction vtx. It does not include propagation time from POT to flux window.

Here are the version of the repository I used when running genie. 
```
sbndcode          v09_53_02       -f Linux64bit+3.10-2.17 -q e20:prof
dk2nugenie        v01_10_00d      -f Linux64bit+3.10-2.17 -q e20:prof    
genie             v3_00_06p       -f Linux64bit+3.10-2.17 -q e20:prof     
```

**Comment by nusense** [comment]
By default it doesn't for v01_10_00.   There's a flag for turning it on, but I also switched the default for v01_10_01.   The other issue is that depending on when/how the gsimple file was generated it might not have the (proton-to-decay) + (decay-to-flux-window) time set.   Older files didn't have a member variable (`vtxt`) for this so it is by default zero when reading into the newer structure of v01_10_00.

Can you do <pre>
genie <your-gsimple-file.root>
flux->Show(0)
</pre>
for example <pre>
=====> EVENT:0
 entry           = (genie::flux::GSimpleNtpEntry*)0x5e7f470
 wgt             = 1
 vtxx            = 1.81728
 vtxy            = 1.59742
 vtxz            = -6.7
 dist            = 340.292
 px              = 0.0140027
 py              = -0.266703
 pz              = 2.60361
 E               = 2.61727
 pdg             = 14
 metakey         = 1724369205
 </pre>
